# Generated by Django 5.0.4 on 2024-05-03 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тактанын аты')),
                ('visibility', models.CharField(choices=[('pr', 'private'), ('pu', 'public')], default='pr', max_length=2)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('assign_users', models.ManyToManyField(blank=True, related_name='assign_boards', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тапшырманын аты')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Суроттомо')),
                ('tag', models.CharField(blank=True, max_length=150, verbose_name='тэг')),
                ('notification_status', models.CharField(choices=[('w', 'w'), ('nw', 'nw')], default='nw', max_length=2)),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='deadline')),
                ('assign_user', models.ManyToManyField(blank=True, related_name='assign_cards', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsCreate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('writed_at', models.DateTimeField(auto_now_add=True)),
                ('replyCommentId', models.IntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_manager.card')),
                ('replyComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='task_manager.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writerComments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-writed_at'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Баракчанын аты')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='task_manager.board')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='task_manager.list'),
        ),
    ]
